steps:
  # 構建Docker映像
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/employee-management-system:latest'
      - '--platform'
      - 'linux/amd64'
      - '.'
    
  # 推送映像到Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/employee-management-system:latest'
    
  # 部署到Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'employee-management-system'
      - '--image'
      - 'gcr.io/$PROJECT_ID/employee-management-system:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080'

timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY