@echo off
echo 🚀 執行手動Google Cloud部署...

echo 🔐 檢查認證...
gcloud auth list

echo 📋 設定專案...
gcloud config set project complete-employee-management-436300

echo 🏗️ 創建 Artifact Registry 儲存庫...
gcloud artifacts repositories create employee-management --repository-format=docker --location=europe-west1

echo 🐳 構建Docker映像...
docker build -t employee-management-system:latest .

echo 🏷️ 標籤映像...
docker tag employee-management-system:latest europe-west1-docker.pkg.dev/complete-employee-management-436300/employee-management/employee-management-system:latest

echo 📤 推送映像...
docker push europe-west1-docker.pkg.dev/complete-employee-management-436300/employee-management/employee-management-system:latest

echo 🚀 部署到Cloud Run...
gcloud run deploy employee-management-system --image europe-west1-docker.pkg.dev/complete-employee-management-436300/employee-management/employee-management-system:latest --platform managed --region europe-west1 --allow-unauthenticated --port 8080 --memory 2Gi --cpu 2

echo ✅ 部署完成！