[build]
builder = "NIXPACKS"

[build.env]
NODE_VERSION = "20"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = {{ PORT }}