{
  "services": [
    {
      "type": "web",
      "name": "employee-management-system",
      "env": "node",
      "buildCommand": "npm install",
      "startCommand": "node app.js",
      "healthCheckPath": "/health",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        },
        {
          "key": "PORT",
          "value": "8080"
        }
      ]
    }
  ]
}